### ISSUE TITLE
Renovation Checklist

### ISSUE THREAD

**Issue by ghost** [TGWaffles/cryopodbot#7]
To-do list, in order of priority:

- [ ] Store credentials properly and move bot code to GitHub again. Environment variables?
- [ ] Add tests. Lots and lots and lots of tests.
- [ ] Design reworkings.
- [ ] The new scheduler. See #9.

**Comment by hatzka-nezumi** [comment]
I think common practice is to put the credentials in a file and gitignore that file
